spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/jpa
    username: postgres
    password: postgres

camel-consulta:
  membros: select nome,bairro,cidade  from membro